apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-canary
  namespace: default
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-canary
  template:
    metadata:
      labels:
        app: rollout-canary
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
     canary:
       steps:
       - setWeight: 20
       - pause: {}
       - setWeight: 40
       - pause: {duration: 10}
       - setWeight: 60
       - pause: {duration: 10}
       - setWeight: 80
       - pause: {duration: 10}
---
kind: Service
apiVersion: v1
metadata:
  name:  rollout-canary-service
  namespace: default
spec:
  selector:
    app:  rollout-canary
  type:  LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort:  8080
