apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bluegreen
  namespace: default
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    blueGreen: 
      activeService: rollout-bluegreen-active
      previewService: rollout-bluegreen-preview
      autoPromotionEnabled: true
---
kind: Service
apiVersion: v1
metadata:
  name:  rollout-bluegreen-active
  namespace: default
spec:
  selector:
    app:  rollout-bluegreen
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort:  8080
---
kind: Service
apiVersion: v1
metadata:
  name:  rollout-bluegreen-preview
  namespace: default
spec:
  selector:
    app:  rollout-bluegreen
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort:  8080
